HMS/Areas/Dashboard/Controllers/AccomodationPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HMS.Areas.Dashboard.ViewModels;
using HMS.Entities;
using HMS.Services;

namespace HMS.Areas.Dashboard.Controllers
{
    public class AccomodationPackagesController : Controller
    {
        
        // GET: Dashboard/AccomodationPackages

        AccomodationPackagesServices accomodationPackagesServices = new AccomodationPackagesServices();
        AccomodationTypesServices accomodationTypesServices = new AccomodationTypesServices();



        public ActionResult Index(string searchterm)
        {
            AccomodationPackagesListingModel model = new AccomodationPackagesListingModel();

            model.SearchTerm = searchterm;

            model.AccomodationPackages = accomodationPackagesServices.SearchAccomodationPackages(searchterm);

            return View(model);
        }

        [HttpGet]
        public ActionResult Action(int? ID)
        {
            AccomodationPackageActionModel model = new AccomodationPackageActionModel();

            if (ID.HasValue)
            {
                //edit a record

                var accomodationPackage = accomodationPackagesServices.GetAccomodationPackageByID(ID.Value);

                model.ID = accomodationPackage.ID;
                model.AccomodationTypeID = accomodationPackage.AccomodationTypeID;
                model.Name = accomodationPackage.Name;
                model.NoOfRoom = accomodationPackage.NoOfRoom;
                model.FeePerNight = accomodationPackage.FeePerNight;
            }

            model.AccomodationTypes = accomodationTypesServices.GetAllAccomodationTypes();

            return PartialView("_Action", model);

        }

        public ActionResult Listing()
        {
            return PartialView("_Listing");

        }

        [HttpPost]
        public JsonResult Action(AccomodationPackageActionModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;

            if (model.ID > 0)
            {
                var accomodationPackage = accomodationPackagesServices.GetAccomodationPackageByID(model.ID);

                accomodationPackage.AccomodationTypeID = model.AccomodationTypeID;
                accomodationPackage.Name = model.Name;
                accomodationPackage.NoOfRoom = model.NoOfRoom;
                accomodationPackage.FeePerNight = model.FeePerNight;

                //edit a record

                result = accomodationPackagesServices.UpdateAccomodationPackage(accomodationPackage);

            }

            else
            {
                AccomodationPackages accomodationPackages = new AccomodationPackages();

                accomodationPackages.AccomodationTypeID = model.AccomodationTypeID;
                accomodationPackages.Name = model.Name;
                accomodationPackages.NoOfRoom = model.NoOfRoom;
                accomodationPackages.FeePerNight = model.FeePerNight;

                result = accomodationPackagesServices.SaveAccomodationPackage(accomodationPackages);

            }

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on AccomodationPackage Type" };
            }

            return json;
        }

        [HttpGet]
        public ActionResult Delete(int ID)
        {
            AccomodationPackageActionModel model = new AccomodationPackageActionModel();

            var accomodationPackage = accomodationPackagesServices.GetAccomodationPackageByID(ID);

            model.ID = accomodationPackage.ID;

            return PartialView("_Delete", model);

        }

        public JsonResult Delete(AccomodationPackageActionModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;

            var accomodationPackage = accomodationPackagesServices.GetAccomodationPackageByID(model.ID);

            result = accomodationPackagesServices.DeleteAccomodationPackage(accomodationPackage);

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on AccomodationPackage Type" };
            }

            return json;
        }


    }
}

HMS/Areas/Dashboard/Controllers/AccomodationTypesController.cs
using HMS.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using HMS.Areas.Dashboard.ViewModels;
using HMS.Entities;

namespace HMS.Areas.Dashboard.Controllers
{
    public class AccomodationTypesController : Controller
    {
        //created a object of AccomodationTypesServices

        AccomodationTypesServices accomodationTypesServices = new AccomodationTypesServices();

        // GET: Dashboard/AccomodationTypes

        public ActionResult Index(string searchterm)
        {
            AccomodationTypesListingModel model = new AccomodationTypesListingModel();

            model.SearchTerm = searchterm;

            model.AccomodationTypes = accomodationTypesServices.SearchAccomodationTypes(searchterm);

            return View(model);
        }

        //public ActionResult Listing()
        //{
        //    AccomodationTypesListingModel model = new AccomodationTypesListingModel();
            
        //     model.AccomodationTypes = accomodationTypesServices.GetAllAccomodationTypes();
            
        //    return PartialView("_Listing",model);
        //}

        [HttpGet]
        public ActionResult Action(int? ID)
        {
            AccomodationTypeActionModel model = new AccomodationTypeActionModel();

            if (ID.HasValue)
            {
                //edit a record

                var accomodationType = accomodationTypesServices.GetAccomodationTypeByID(ID.Value);

                model.ID = accomodationType.ID;
                model.Name = accomodationType.Name;
                model.Description = accomodationType.Description;
            }

            return PartialView("_Action",model);

        }

        [HttpPost]
        public JsonResult Action(AccomodationTypeActionModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;

            if (model.ID > 0)
            {
                var accomodationType = accomodationTypesServices.GetAccomodationTypeByID(model.ID);

                accomodationType.Name = model.Name;
                accomodationType.Description = model.Description;

                //edit a record

                result = accomodationTypesServices.UpdateAccomodationType(accomodationType);

            }

            else
            {
                AccomodationType accomodationType = new AccomodationType();

                accomodationType.Name = model.Name;
                accomodationType.Description = model.Description;

                result = accomodationTypesServices.SaveAccomodationType(accomodationType);

            }

            if (result)
            {
                json.Data = new {Success = true};
            }
            else
            {
                json.Data = new {Success = false, Message = "Unable to perform action on Accomodation Type"};
            }

            return json;
        }

        [HttpGet]
        public ActionResult Delete(int ID)
        {
            AccomodationTypeActionModel model = new AccomodationTypeActionModel();

            var accomodationType = accomodationTypesServices.GetAccomodationTypeByID(ID);

            model.ID = accomodationType.ID;
            
            return PartialView("_Delete", model);

        }

        public JsonResult Delete(AccomodationTypeActionModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;
            
            var accomodationType = accomodationTypesServices.GetAccomodationTypeByID(model.ID);

            result = accomodationTypesServices.DeleteAccomodationType(accomodationType);

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Type" };
            }

            return json;
        }

    }
}

HMS/Areas/Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title -HMS </title>


    <link href="~/Areas/Dashboard/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Areas/Dashboard/Content/css/simple-sidebar.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <script src="~/Areas/Dashboard/Content/vendor/jquery/jquery.min.js"></script>

</head>

<body>

<div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
        <div class="sidebar-heading"> <i class="fas fa-hotel mr-1"></i>HMS </div>
        <div class="list-group list-group-flush">
            <a href="@Url.Action("Index","AccomodationTypes")" class="list-group-item list-group-item-action bg-light">
                <i class="fas fa-building mr-1"></i> Accomodation Types
            </a>
           <a href="@Url.Action("Index","AccomodationPackages")" class="list-group-item list-group-item-action bg-light">
                <i class="fas fa-building mr-1"></i> Accomodation Packages
            </a>
            <a href="@Url.Action("Index","Roles")" class="list-group-item list-group-item-action bg-light">
                <i class="fas fa-users-cog mr-1"></i> Roles
            </a>
            <a href="@Url.Action("Index","Users")" class="list-group-item list-group-item-action bg-light">
                <i class="fas fa-user mr-1"></i> Users
            </a>
             
        </div>
    </div>
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">

        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            <button class="btn btn-primary" id="menu-toggle">
                <i class="fas fa-bars"></i>
            </button>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">
                            <i class="fas fa-sign-out-alt"></i> Log Out 
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container-fluid">
            @RenderBody()

        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>

    @using (Html.BeginForm("LogOff", "Account", new {area = ""},FormMethod.Post,new { id = "logoutForm", @class = "navbar-right" }))
    {
    
        @Html.AntiForgeryToken()
    }

<!-- /#wrapper -->

    <script src="~/Areas/Dashboard/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
$("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });</script>

</body>

</html>